[package]
name = "resilience"
version = "0.1.0"
authors = ["Dmitry Galinsky <dima.exe@gmail.com>"]
publish = false

[dependencies]
futures = "0.1"
tokio-timer = "0.2"
tokio-executor = "0.1"
rand = "0.5"

[dev-dependencies]
rayon = "1.0"
tokio = "0.1.8"
tokio-threadpool = "0.1.6"
