[package]
name = "failsafe"
version = "0.1.0"
authors = ["Dmitry Galinsky <dima.exe@gmail.com>"]
description = "A circuit breaker implementation"
license = "MIT"
repository = "https://github.com/dmexe/failsafe-rs"

[dependencies]
futures = "0.1"
rand = "0.5"

[dev-dependencies]
tokio = "0.1.8"
tokio-threadpool = "0.1.6"
