[package]
name = "resilience"
version = "0.1.0"
authors = ["Dmitry Galinsky <dima.exe@gmail.com>"]
description = "A circuit breaker implementation"
license = "MIT"
repository = "https://github.com/dmexe/resilience-rs"

[dependencies]
futures = "0.1"
tokio-timer = "0.2"
rand = "0.5"

[dev-dependencies]
rayon = "1.0"
tokio = "0.1.8"
tokio-executor = "0.1"
tokio-threadpool = "0.1.6"
