version: 2

default_env: &default_env
  environment:
    CARGO_HOME: "/root/.cargo"
    CARGO: "cargo --color always"
    CARGO_ARGS: ""

default_steps: &default_steps
  steps:
    - checkout
    - run:
        name: "Print versions"
        command: .circleci/cache-key /root/.cache-key
    - restore_cache:
        key: cache-v1-{{ checksum "/root/.cache-key" }}-{{ checksum "./Cargo.toml" }}
    - run:
        name: "Check formatting"
        command: .circleci/cargo-fmt-check
    - run:
        name: "Fetch dependencies"
        command: ${CARGO} fetch
    - run:
        name: "Build"
        command: ${CARGO} build ${CARGO_ARGS}
    - run:
        name: "Test"
        command: ${CARGO} test ${CARGO_ARGS} -- --nocapture
    - save_cache:
        key: cache-v3-{{ checksum "/root/.cache-key" }}-{{ checksum "./Cargo.toml" }}
        paths:
          - "/root/.cargo"
          - "./target"
jobs:
  rust_1_26:
    <<: *default_env
    <<: *default_steps
    docker:
    - image: "rust:1.26"

  rust_1_28:
    <<: *default_env
    <<: *default_steps
    docker:
    - image: "rust:1.28"

  rust_nightly:
    <<: *default_env
    <<: *default_steps
    docker:
    - image: "rustlang/rust:nightly"

workflows:
  version: 2
  commit:
    jobs:
    - rust_1_26
    - rust_1_28
    - rust_nightly
  nightly:
    jobs:
    - rust_nightly
    triggers:
    - schedule:
        cron: "0 0 * * *"
        filters: { branches: { only: [master] } }
